export * from "./Auth.Routes"
export * from "./Blog.Routes"
export * from "./Tag.Routes"
export * from "./Question.Routes"
export * from "./Answer.Routes"
export * from "./Like.Routes"
export * from "./comment.Routes"
export * from "./Link.Routes"